image: maven:3.9.5
cache:
  paths:
    - target/
stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - target/*.jar
  script:
    - mvn clean package

deploy:
  stage: deploy
  script:
    - apt update
    - apt install openssh-client -y
    - mkdir -p ~/.ssh
    - cp "$ssh_key" ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - host0=`awk '{print $1}' <<< $host`
    - scp -oStrictHostKeyChecking=no ./target/*.jar "$user"@"$host0":"$deployDirectory"
    - cp "$application_yml" application.yml
    - |
      echo -e "\nversion: $CI_COMMIT_SHORT_SHA" >> application.yml
    - scp application.yml "$user"@"$host0":"$deployDirectory"/application.yml
    - scp "$restart_script" "$user"@"$host0":"$deployDirectory"/restart.sh

    - >
      for host in $host; do
        ssh -oStrictHostKeyChecking=no "$user"@"$host" "bash $deployDirectory/restart.sh"
      done
