image: maven:3.9.5-eclipse-temurin-21
# Commented out to make sure build-beta and build-prod are not conflicting one another
#cache:
#  paths:
#    - target/

stages:
  - build
  - deploy

.build-template: &build-template
  stage: build
  artifacts:
    paths:
      - target/*.jar
  before_script:
    - apt-get update
    - apt-get install -y libatomic1
  script:
    # Copy VITE_CONFIG file variable into frontend/.env
    - cp "$VITE_CONFIG" frontend/.env
    - echo "Using VITE config:"
    - cat frontend/.env
    - mvn clean package

build-beta:
  <<: *build-template
  environment: beta
  only:
    - main

build-prod:
  <<: *build-template
  environment: prod
  only:
    - main

.deploy-template: &deploy-template
  stage: deploy
  script:
    - apt update
    - apt install openssh-client -y
    - mkdir -p ~/.ssh
    - cp "$ssh_key" ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - host0=`awk '{print $1}' <<< $host`
    - scp -oStrictHostKeyChecking=no ./target/*.jar "$user"@"$host0":"$deployDirectory"
    - cp "$application_yml" application.yml
    - |
      echo -e "\nversion: $CI_COMMIT_SHORT_SHA" >> application.yml
    - scp application.yml "$user"@"$host0":"$deployDirectory"/application.yml
    - scp "$restart_script" "$user"@"$host0":"$deployDirectory"/restart.sh

    - >
      for host in $host; do
        ssh -oStrictHostKeyChecking=no "$user"@"$host" "bash $deployDirectory/restart.sh"
      done

deploy-beta:
  <<: *deploy-template
  environment: beta
  needs:
    - build-beta
  only:
    - main
  when: manual

deploy-prod:
  <<: *deploy-template
  environment: prod
  needs:
    - build-prod
  only:
    - main
  when: manual
