export type OrganismOption = {
  name: string;
  id: string;
};

export const organismDefaultOptions: OrganismOption[] = [
  { name: 'Homo sapiens (human)', id: 'NCBITaxon_9606' },
  { name: 'Mus musculus (mouse)', id: 'NCBITaxon_10090' },
  { name: 'Arabidopsis thaliana (thale cress)', id: 'NCBITaxon_3702' },
  { name: 'Rattus norvegicus (brown rat)', id: 'NCBITaxon_10116' },
  { name: 'Drosophila melanogaster (fruit fly)', id: 'NCBITaxon_7227' },
  { name: 'Oryza sativa (common rice)', id: 'NCBITaxon_4530' },
  { name: 'Anas platyrhynchos (mallard)', id: 'NCBITaxon_8839' },
  { name: 'Anolis carolinensis (anole)', id: 'NCBITaxon_28377' },
  { name: 'Anopheles gambiae (African malaria mosquito)', id: 'NCBITaxon_7165' },
  { name: 'Arabidopsis lyrata (rock cress)', id: 'NCBITaxon_59689' },
  { name: 'Aspergillus fumigatus', id: 'NCBITaxon_746128' },
  { name: 'Bos taurus (cow)', id: 'NCBITaxon_9913' },
  { name: 'Brachypodium distachyon (stiff brome)', id: 'NCBITaxon_15368' },
  { name: 'Brassica oleracea (cabbage)', id: 'NCBITaxon_3712' },
  { name: 'Brassica rapa (turnip)', id: 'NCBITaxon_3711' },
  { name: 'Caenorhabditis elegans', id: 'NCBITaxon_6239' },
  { name: 'Canis familiaris (dog)', id: 'NCBITaxon_9615' },
  { name: 'Chlorocebus sabaeus (green monkey)', id: 'NCBITaxon_60711' },
  { name: 'Ciona intestinalis (sea squirt)', id: 'NCBITaxon_7719' },
  { name: 'Ciona savignyi (Pacific sea squirt)', id: 'NCBITaxon_51511' },
  { name: 'Danio rerio (zebrafish)', id: 'NCBITaxon_7955' },
  { name: 'Dasypus novemcinctus (nine-banded armadillo)', id: 'NCBITaxon_9361' },
  { name: 'Equus caballus (horse)', id: 'NCBITaxon_9796' },
  { name: 'Gallus gallus (chicken)', id: 'NCBITaxon_9031' },
  { name: 'Glycine max (soybean)', id: 'NCBITaxon_3847' },
  { name: 'Gorilla gorilla', id: 'NCBITaxon_9593' },
  { name: 'Hordeum vulgare (barley)', id: 'NCBITaxon_4513' },
  { name: 'Macaca mulatta (rhesus monkey)', id: 'NCBITaxon_9544' },
  { name: 'Medicago truncatula (barrel clover)', id: 'NCBITaxon_3880' },
  { name: 'Monodelphis domestica (short-tailed opossum)', id: 'NCBITaxon_13616' },
  { name: 'Musa acuminata (banana)', id: 'NCBITaxon_4641' },
  { name: 'Ornithorhynchus anatinus (platypus)', id: 'NCBITaxon_9258' },
  { name: 'Oryctolagus cuniculus (rabbit)', id: 'NCBITaxon_9986' },
  { name: 'Oryza rufipogon (brownbeard rice)', id: 'NCBITaxon_4529' },
  { name: 'Ovis aries (sheep)', id: 'NCBITaxon_9940' },
  { name: 'Pan troglodytes (chimpanzee)', id: 'NCBITaxon_9598' },
  { name: 'Papio anubis (baboon)', id: 'NCBITaxon_9555' },
  { name: 'Physcomitrella patens (moss)', id: 'NCBITaxon_3218' },
  { name: 'Pongo abelii (orangutan)', id: 'NCBITaxon_9601' },
  { name: 'Populus trichocarpa (poplar tree)', id: 'NCBITaxon_3694' },
  { name: 'Saccharomyces cerevisiae (brewer\'s yeast)', id: 'NCBITaxon_4932' },
  { name: 'Schistosoma mansoni (blood fluke)', id: 'NCBITaxon_6183' },
  { name: 'Schizosaccharomyces pombe (fission yeast)', id: 'NCBITaxon_4896' },
  { name: 'Solanum lycopersicum (tomato)', id: 'NCBITaxon_4081' },
  { name: 'Solanum tuberosum (potato)', id: 'NCBITaxon_4113' },
  { name: 'Sorghum bicolor', id: 'NCBITaxon_4558' },
  { name: 'Sus scrofa (pig)', id: 'NCBITaxon_9823' },
  { name: 'Tetraodon nigroviridis (green pufferfish)', id: 'NCBITaxon_99883' },
  { name: 'Theobroma cacao (chocolate)', id: 'NCBITaxon_3641' },
  { name: 'Triticum aestivum (wheat)', id: 'NCBITaxon_4565' },
  { name: 'Vitis vinifera (grape)', id: 'NCBITaxon_29760' },
  { name: 'Xenopus tropicalis (frog)', id: 'NCBITaxon_8364' },
  { name: 'Yarrowia lipolytica', id: 'NCBITaxon_4952' },
  { name: 'Zea mays (corn)', id: 'NCBITaxon_4577' },
];

export const organismNames = organismDefaultOptions.map(({ name }) => name);
