import SanitizeModal from '@/components/SanitizeModal.vue';
import { createApp, h } from 'vue';

export const nonSafePathRegex = /[^a-zA-Z0-9!\-_.*'()/ ]| {2,}/g;
export const forbiddenPathChars: [RegExp, string, string?][] = [
  [/&/g, 'Et'],
  [/\$/g, 'S'],
  [/\p{C}/gu, ''],
  [/@/g, 'A'],
  [/=/g, '-'],
  [/;/g, '-'],
  [/:/g, '-'],
  [/\+/g, '--'],
  [/,/g, '-'],
  [/\?/g, '-'],
  [/\\/g, '-'],
  [/{/g, '('],
  [/\[/g, '('],
  [/\^/g, '-'],
  [/}/g, ')'],
  [/]/g, ')'],
  [/%/g, '-'],
  [/`/g, '-'],
  [/"/g, '\''],
  [/>/g, ')'],
  [/</g, '('],
  [/~/g, '-'],
  [/#/g, '-'],
  [/\|/g, 'I'],
  [/\s{2,}/g, ' ', '2 x " "'], // Important: this must be the last replacement to cover up for the double spaces potentially generated by previous replacements
];


export type Replacement = { replacement: string, examples: string[], toString?: string };
export const sanitizeString = (toSanitize: string, replacementList: [RegExp, Replacement][]) => {
  return replacementList.reduce((s, [badChar, {replacement}]) => s.replaceAll(badChar, replacement), toSanitize);
};


type ModalInstance = InstanceType<typeof SanitizeModal>

export async function provideReplacements(replacements: [RegExp, Replacement][]): Promise<[RegExp, Replacement][]> {
  return new Promise((resolve, reject) => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    const app = createApp({
      render() {
        return h(SanitizeModal, {
          replacements,
          onClose: () => {
            reject('cancelled');
            cleanUp();
          },
          onSave: (replacements: [RegExp, Replacement][]) => {
            resolve(replacements);
            cleanUp();
          },
        } as unknown as ModalInstance['$props']);
      },
    });

    const cleanUp = () => {
      setTimeout(() => {
        app.unmount();
        container.remove();
      }, 0);
    };
    app.mount(container);
  });
}
